modLoader="javafml"
loaderVersion="[41,)"
issueTrackerURL="https://github.com/VazkiiMods/Zeta"
license="https://github.com/VazkiiMods/Zeta/blob/master/LICENSE.md"

[[mods]]
modId="zeta"
displayName="Zeta"
version="${file.jarVersion}"
authors="Vazkii, quat, iThundxr, siuol, wiresegal, MehVahdJukaar"
description='''A fully featured Library designed around loading highly configurable, agile developed. modular mods'''

[[dependencies.zeta]]
    modId="forge"
    mandatory=true
    versionRange="[43.0.8,)"
    ordering="AFTER"
    side="BOTH"