modLoader="javafml"
loaderVersion="[3,)"
issueTrackerURL="https://github.com/VazkiiMods/Zeta"
license="https://github.com/VazkiiMods/Zeta/blob/master/LICENSE.md"

[[mods]]
modId="zeta"
displayName="Zeta"
version="${file.jarVersion}"
authors="Vazkii, quat, IThundxr, siuol, wiresegal, MehVahdJukaar"
description='''A fully featured Library designed around loading highly configurable, agile developed. modular mods'''

[[mixins]]
config="zeta.mixins.json"

[[mixins]]
config="zeta_forge.mixins.json"

file="META-INF/accesstransformer.cfg"

[[dependencies.zeta]]
    modId="neoforge"
    type="required"
    versionRange="[21.0.10,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.zeta]]
    modId="quark"
    mandatory=false
    versionRange="[4.0-461,)"
    side="BOTH"